name: Buscador de Ofertas LovaGame

on:
  workflow_dispatch: # Permite botón manual
  schedule:
    - cron: '5 * * * *'  # Ejecuta en el minuto 5 de cada hora

jobs:
  buscar-juegos:
    runs-on: ubuntu-latest
    # Necesitamos permisos para que el bot pueda hacer el "push" al historial.txt
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Instalar Java
        uses: actions/setup-java@v4 # Actualizado a v4
        with:
          distribution: 'temurin' # He cambiado a temurin, suele dar menos líos en GitHub
          java-version: '17'
          cache: 'maven' # <<--- ESTO ES LO MÁS IMPORTANTE. Evita el error 403.

      - name: Ejecutar LovaGame
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: "@lovagame_rodrigo"
        run: mvn --batch-mode clean compile exec:java -Dexec.mainClass="com.rodrigo.lovagame.Main"

      - name: Guardar cambios en historial.txt
        run: |
          git config --global user.name 'LovaGame Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add historial.txt
          # El commit solo se hace si hay cambios reales en el archivo
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizando historial" && git push)
