name: Buscador de Ofertas LovaGame

on:
  workflow_dispatch: # Permite botón manual
  schedule:
    - cron: '5 * * * *'  # Ejecuta en el minuto 5 de cada hora

jobs:
  buscar-juegos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Ejecutar LovaGame
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: "@lovagame_rodrigo"
        run: mvn clean compile exec:java -Dexec.mainClass="com.rodrigo.lovagame.Main"

      - name: Guardar cambios en historial.txt
        run: |
          git config --global user.name 'LovaGame Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add historial.txt
          git commit -m "Actualizando historial" || exit 0
          git push
